"""travelprep-mcp server -- FastMCP 3.4+ tools mounted under FastAPI.

Migrated 2026-07-14 from bare Starlette (mcp.custom_route) to FastAPI so
the webapp's ApiDocsPage gets real, auto-generated Swagger UI / ReDoc --
per WEBAPP_SOTA_STANDARDS.md §IX, that page is FastAPI-only and Starlette
servers should not have Swagger manually wired in. This mirrors the
fleet reference pattern in arxiv-mcp/src/arxiv_mcp/app.py (see
mcp-central-docs/standards/FASTMCP_FEATURES.md §1 and CORS_STANDARD.md).

MCP tools:
    stays(operation, provider, ...)        -- Airbnb / Booking.com search+details
    hotel_extras(operation, ...)           -- Booking.com-only: find_hotels,
                                               compare, check_availability,
                                               reviews, price_calendar
    account(operation)                     -- Booking.com trips/wishlist/rewards
                                               via a locally-persisted login
                                               session (see auth/booking_session.py)
    destination(operation, place, ...)     -- free-source destination info

MCP resources:
    skill://travelprep-expert/SKILL.md     -- skill content, MCP resource form

REST (FastAPI, HTTP transport only):
    GET  /api/capabilities                 -- mandatory capability introspection
    GET  /api/tools                        -- dynamic tool list for Tools Hub
    GET  /api/health                       -- liveness
    GET  /api/skills                       -- list registered skills
    GET  /skill/{name}                     -- raw SKILL.md content for one skill
    GET  /api/llm/discover                 -- local Ollama/LM Studio auto-detection
    GET  /docs, /redoc, /openapi.json      -- auto-generated by FastAPI

MCP endpoint (mounted, not a REST route):
    ALL  /mcp/...                          -- streamable HTTP MCP transport

Run:
    uv run travelprep-mcp                  # stdio (default, for Claude Desktop etc)
    MCP_TRANSPORT=http uv run travelprep-mcp   # FastAPI + mounted MCP, port 11099
"""

from __future__ import annotations

import os
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path

import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import PlainTextResponse
from fastmcp import FastMCP

from travelprep_mcp import __version__, llm_discovery
from travelprep_mcp.tools.account import account as account_impl
from travelprep_mcp.tools.destination import destination as destination_impl
from travelprep_mcp.tools.hotel_extras import hotel_extras as hotel_extras_impl
from travelprep_mcp.tools.stays import stays as stays_impl

_READ_ONLY = {"readonly": True}
_SKILLS_DIR = Path(__file__).parent / "skills"
_PRIMARY_SKILL = "travelprep-expert"

mcp = FastMCP(
    name="travelprep-mcp",
    instructions=(
        "Trip preparation tools: search and inspect accommodation listings "
        "on Airbnb and Booking.com (stays, hotel_extras tools), and pull "
        "free-source destination info -- overview, weather, "
        "practical/currency/language facts (destination tool). No paid API "
        "keys required for anything in this server."
    ),
)


@mcp.tool(annotations=_READ_ONLY)
async def stays(
    operation: str,
    provider: str,
    location: str | None = None,
    listing_id: str | None = None,
    checkin: str | None = None,
    checkout: str | None = None,
    adults: int = 1,
    children: int = 0,
    min_price: int | None = None,
    max_price: int | None = None,
) -> dict:
    """Search or fetch details for accommodation via Airbnb or Booking.com.

    operation: "search" | "details"
    provider: "airbnb" | "booking"
    """
    return await stays_impl(
        operation=operation,  # type: ignore[arg-type]
        provider=provider,  # type: ignore[arg-type]
        location=location,
        listing_id=listing_id,
        checkin=checkin,
        checkout=checkout,
        adults=adults,
        children=children,
        min_price=min_price,
        max_price=max_price,
    )


@mcp.tool(annotations=_READ_ONLY)
async def hotel_extras(
    operation: str,
    location: str | None = None,
    hotel_url: str | None = None,
    hotel_urls: list[str] | None = None,
    checkin: str | None = None,
    checkout: str | None = None,
    adults: int = 2,
    rooms: int = 1,
    filters: dict | None = None,
    sort_by: str = "recent",
    filter_by: str | None = None,
    price_calendar_start: str | None = None,
    price_calendar_nights: int = 14,
) -> dict:
    """Booking.com-only extras beyond basic search/details.

    operation: "find_hotels" | "compare" | "check_availability" | "reviews" | "price_calendar"
    """
    return await hotel_extras_impl(
        operation=operation,  # type: ignore[arg-type]
        location=location,
        hotel_url=hotel_url,
        hotel_urls=hotel_urls,
        checkin=checkin,
        checkout=checkout,
        adults=adults,
        rooms=rooms,
        filters=filters,
        sort_by=sort_by,
        filter_by=filter_by,
        price_calendar_start=price_calendar_start,
        price_calendar_nights=price_calendar_nights,
    )


@mcp.tool(annotations=_READ_ONLY)
async def account(operation: str) -> dict:
    """Booking.com account access -- trips, wishlist, rewards.

    operation: "login" | "status" | "trips" | "wishlist" | "rewards"

    Uses a locally-persisted, isolated login session (never Sandra's
    live default browser profile) -- run operation="login" once first.
    No booking-execution capability exists anywhere in this server.
    """
    return await account_impl(operation=operation)  # type: ignore[arg-type]


@mcp.tool(annotations=_READ_ONLY)
async def destination(
    operation: str,
    place: str,
    forecast_days: int = 7,
) -> dict:
    """Free-source destination info.

    operation: "overview" | "weather" | "practical" | "full"
    """
    return await destination_impl(
        operation=operation,  # type: ignore[arg-type]
        place=place,
        forecast_days=forecast_days,
    )


@mcp.resource(f"skill://{_PRIMARY_SKILL}/SKILL.md")
def get_travelprep_expert_skill() -> str:
    """The travelprep-expert skill content, as an MCP resource."""
    path = _SKILLS_DIR / _PRIMARY_SKILL / "SKILL.md"
    return path.read_text(encoding="utf-8") if path.exists() else "not found"


# --- FastAPI app: REST layer + mounted MCP (HTTP transport only) -----------

_start_time: float = 0.0


class _MCPWrapper:
    """Fixes a trailing-slash mismatch when mounting mcp.http_app() under FastAPI.

    mcp.http_app(path="/") expects requests at exactly "/" internally, but
    a mount at "/mcp" strips the prefix and leaves an empty path for a
    request to "/mcp" (no trailing slash). Force the trailing slash so the
    internal route always matches. Same pattern as arxiv-mcp's app.py.
    """

    def __init__(self, asgi_app):
        self.asgi_app = asgi_app

    async def __call__(self, scope, receive, send):
        if scope["type"] == "http":
            path = scope.get("path", "")
            if not path.endswith("/") and path != "":
                scope["path"] = path + "/"
                if scope.get("raw_path"):
                    scope["raw_path"] = scope["raw_path"] + b"/"
        await self.asgi_app(scope, receive, send)


def build_app() -> FastAPI:
    """Build the FastAPI app: REST routes + mounted MCP streamable-HTTP transport."""
    global _start_time
    _start_time = datetime.now(timezone.utc).timestamp()

    mcp_http = mcp.http_app(path="/")

    @asynccontextmanager
    async def _lifespan(app: FastAPI):
        async with mcp_http.lifespan(app):
            yield

    app = FastAPI(
        title="travelprep-mcp",
        version=__version__,
        lifespan=_lifespan,
    )

    # CORS: local dev server + Tauri webview + tailnet. See CORS_STANDARD.md --
    # no allow_origins=["*"], since allow_credentials=True makes that a
    # browser-enforced impossibility anyway.
    app.add_middleware(
        CORSMiddleware,
        allow_origins=[
            "http://127.0.0.1:11100",
            "http://localhost:11100",
            "http://tauri.localhost",
            "https://tauri.localhost",
            "tauri://localhost",
        ],
        allow_origin_regex=(
            r"https?://(?:[a-zA-Z0-9-]+\.ts\.net|tauri\.localhost|localhost"
            r"|127\.0\.0\.1|192\.168\.\d{1,3}\.\d{1,3}|10\.\d{1,3}\.\d{1,3}\.\d{1,3}"
            r"|100\.\d{1,3}\.\d{1,3}\.\d{1,3})(?::\d+)?$|^tauri://localhost$"
        ),
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.get("/api/capabilities")
    async def api_capabilities() -> dict:
        """Mandatory capability introspection endpoint (WEBAPP_STANDARDS.md §1.4)."""
        tools = await mcp.list_tools()

        portmanteau_tools = []
        atomic_tools = []
        for t in tools:
            props = (t.parameters or {}).get("properties", {})
            op_schema = props.get("operation", {})
            has_operation = isinstance(op_schema, dict) and "enum" in op_schema
            if has_operation:
                portmanteau_tools.append(t.name)
            else:
                atomic_tools.append(t.name)

        return {
            "status": "ok",
            "server": {
                "name": "travelprep-mcp",
                "version": __version__,
                "fastmcp": "3.4+",
            },
            "tool_surface": {
                "total": len(tools),
                "portmanteau_count": len(portmanteau_tools),
                "atomic_count": len(atomic_tools),
                "portmanteau_tools": portmanteau_tools,
                "atomic_tools": atomic_tools,
            },
            "features": {
                "sampling": False,
                "agentic_workflows": False,
                "prompts": False,
                "resources": True,
                "skills": True,
            },
            "inventory": {
                "workflow_tools": [],
                "prompt_names": [],
                "resource_uris": [f"skill://{_PRIMARY_SKILL}/SKILL.md"],
                "skill_uris": [f"skill://{_PRIMARY_SKILL}/SKILL.md"],
            },
            "runtime": {
                "transport": "dual",
                "surface_mode": "portmanteau",
            },
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    @app.get("/api/health")
    async def api_health() -> dict:
        return {
            "status": "ok",
            "version": __version__,
            "uptime_seconds": int(datetime.now(timezone.utc).timestamp() - _start_time),
        }

    @app.get("/api/tools")
    async def api_tools() -> list[dict]:
        """Dynamic tool list for the Tools Hub -- never hardcode this in the frontend."""
        tools = await mcp.list_tools()
        return [
            {
                "name": t.name,
                "description": t.description,
                "input_schema": t.parameters,
            }
            for t in tools
        ]

    @app.get("/api/skills")
    async def api_skills() -> dict:
        """List registered skills (WEBAPP_SOTA_STANDARDS.md §V)."""
        if not _SKILLS_DIR.exists():
            return {"skills": []}
        skills = []
        for skill_dir in sorted(_SKILLS_DIR.iterdir()):
            skill_file = skill_dir / "SKILL.md"
            if skill_file.exists():
                first_line = skill_file.read_text(encoding="utf-8").splitlines()[0].lstrip("# ")
                skills.append(
                    {
                        "id": skill_dir.name,
                        "name": skill_dir.name,
                        "description": first_line,
                        "uri": f"skill://{skill_dir.name}/SKILL.md",
                    }
                )
        return {"skills": skills}

    @app.get("/skill/{skill_name}")
    async def get_skill(skill_name: str) -> PlainTextResponse:
        """Raw SKILL.md content for one skill (WEBAPP_SOTA_STANDARDS.md §V)."""
        skill_path = _SKILLS_DIR / skill_name / "SKILL.md"
        if skill_path.exists():
            return PlainTextResponse(skill_path.read_text(encoding="utf-8"))
        return PlainTextResponse("not found", status_code=404)

    @app.get("/api/llm/discover")
    async def api_llm_discover() -> dict:
        """Local Ollama/LM Studio auto-detection (WEBAPP_SOTA_STANDARDS.md §VI, 'Glom On')."""
        return await llm_discovery.discover()

    # Mount MCP streamable-HTTP transport last so /docs, /redoc, /openapi.json
    # (auto-generated from the routes above) aren't shadowed by the mount.
    app.mount("/mcp", _MCPWrapper(mcp_http), name="mcp")

    return app


def main() -> None:
    transport = os.environ.get("MCP_TRANSPORT", "stdio").lower()
    if transport == "http":
        # Direct uvicorn on the fully-built FastAPI app -- NOT mcp.run_http_async(),
        # which spawns its own internal app and silently drops CORS/custom routes.
        # See CORS_STANDARD.md "FastMCP run_http_async() pitfall".
        uvicorn.run(build_app(), host="127.0.0.1", port=11099, log_level="info")
    else:
        mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
